package constants

const EXTERNAL_URL string = "https://polymorphs.universe.xyz/polymorphs/"
const GENES_COUNT = 9
const BACKGROUND_GENE_COUNT int = 12
const BASE_GENES_COUNT int = 11
const SHOES_GENES_COUNT int = 25
const PANTS_GENES_COUNT int = 33
const TORSO_GENES_COUNT int = 34
const EYEWEAR_GENES_COUNT int = 13
const HEAD_GENES_COUNT int = 31
const WEAPON_RIGHT_GENES_COUNT int = 32
const WEAPON_LEFT_GENES_COUNT int = 32

const LEFT_HAND_GENE_START_IDX = -18
const LEFT_HAND_GENE_END_IDX = -16

const RIGHT_HAND_GENE_START_IDX = -16
const RIGHT_HAND_GENE_END_IDX = -14

const HEAD_GENE_START_IDX = -14
const HEAD_GENE_END_IDX = -12

const EYEWEAR_GENE_START_IDX = -12
const EYEWEAR_GENE_END_IDX = -10

const SHOES_GENE_START_IDX = -10
const SHOES_GENE_END_IDX = -8

const TORSO_GENE_START_IDX = -8
const TORSO_GENE_END_IDX = -6

const PANTS_GENE_START_IDX = -6
const PANTS_GENE_END_IDX = -4

const BACKGROUND_GENE_START_IDX = -4
const BACKGROUND_GENE_END_IDX = -2

const CHARACTER_GENE_START_IDX = -2
const CHARACTER_GENE_END_IDX = 0
